from typing import TypedDict
from langgraph.graph import StateGraph, END
from google import genai
from app.core.config import settings
from datetime import datetime

client = genai.Client(api_key=settings.gemini_api_key)

class AgentState(TypedDict):
    diff: str
    pr_title: str
    pr_number: int
    repo_name: str
    base_branch: str
    head_branch: str
    summary: str
    changelog_entry: str

def analyze_diff(state: AgentState) -> AgentState:
    prompt = f"""You are a senior software engineer reviewing a pull request.
Your job is to write a detailed, human-readable summary of the code changes.
Think about WHY changes were made, not just WHAT changed.
Write for two audiences: senior engineers who want depth, and junior developers who need context.

CRITICAL RULES:
- Only reference files that explicitly appear in the diff below
- Never invent file names, function names, or project structure
- Never assume what files exist outside of what the diff shows
- If the diff is small, keep the analysis proportionally concise
- Base every statement strictly on evidence in the diff

PR Title: {state['pr_title']}
Repository: {state['repo_name']}
Merging: {state['head_branch']} into {state['base_branch']}

Code diff:
{state['diff'][:15000]}

Respond in exactly this markdown format:

## 🤖 Repo Brain Analysis

### What this PR does
[2-3 sentences explaining the overall purpose and approach. Focus on the WHY, not just the what. Base this strictly on the diff above.]

### Why it matters
[1-2 sentences on the business or technical value. What problem does it solve?]

### What changed in each file
[For each file that appears in the diff, one bullet point explaining that file's specific role in this change. Only list files you can see in the diff.]

### Breaking changes
[Any breaking changes visible in the diff. Write "None" if there are none.]

### Things to look at
[2-3 specific things a reviewer should pay attention to based on the actual code in the diff — potential bugs, hardcoded values, security concerns. Only reference what you can see.]

---
*Generated by repo-brain · {state['repo_name']} · PR #{state['pr_number']}*"""
    
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    state["summary"] = response.text
    return state

def write_changelog(state: AgentState) -> AgentState:
    today = datetime.now().strftime("%Y-%m-%d")

    prompt = f"""You are a technical writer maintaining a project changelog.
Based on this PR analysis, write a single concise changelog entry.

CRITICAL RULES:
- Only reference files explicitly mentioned in the summary below
- Never invent file names or project structure
- Keep it factual and grounded in the actual changes

PR Title: {state['pr_title']}
PR Number: {state['pr_number']}
Branch: {state['head_branch']}
Summary: {state['summary']}

Write a changelog entry in exactly this format:

## [{today}] - PR #{state['pr_number']}

**{state['pr_title']}**

[2-3 sentences describing what changed and why. Be specific and technical but concise. Only reference files from the summary above.]

**Files changed:** [only files explicitly mentioned in the summary above]
**Type:** [one of: feature, bugfix, refactor, docs, chore]

---"""
    
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    state["changelog_entry"] = response.text
    return state

def build_doc_agent():
    workflow = StateGraph(AgentState)

    workflow.add_node("analyze_diff", analyze_diff)
    workflow.add_node("write_changelog", write_changelog)

    workflow.set_entry_point("analyze_diff")
    workflow.add_edge("analyze_diff", "write_changelog")
    workflow.add_edge("write_changelog", END)

    return workflow.compile()

doc_agent = build_doc_agent()