from typing import TypedDict
from langgraph.graph import StateGraph, END
from google import genai
from app.core.config import settings

client = genai.Client(api_key=settings.gemini_api_key)

class AgentState(TypedDict):
    diff: str
    pr_title: str
    pr_number: int
    repo_name: str
    base_branch: str
    head_branch: str
    summary: str

def analyze_diff(state: AgentState) -> AgentState:
    prompt = f"""You are a senior software engineer reviewing a pull request.
Your job is to write a detailed, human-readable summary of the code changes.
Think about WHY changes were made, not just WHAT changed.
Write for two audiences: senior engineers who want depth, and junior developers who need context.

PR Title: {state['pr_title']}
Repository: {state['repo_name']}
Merging: {state['head_branch']} into {state['base_branch']}

Code diff:
{state['diff'][:8000]}

Respond in exactly this markdown format:

## 🤖 Repo Brain Analysis

### What this PR does
[2-3 sentences explaining the overall purpose and approach. Focus on the WHY, not just the what.]

### Why it matters
[1-2 sentences on the business or technical value. What problem does it solve?]

### What changed in each file
[For each file modified, one bullet point explaining that file's specific role in this change.]

### Breaking changes
[Any breaking changes, removed functions, changed interfaces. Write "None" if there are none.]

### Things to look at
[2-3 specific things a reviewer should pay attention to — potential bugs, hardcoded values, security concerns. Be specific to the actual code.]

---
*Generated by repo-brain · {state['repo_name']} · PR #{state['pr_number']}*"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    state["summary"] = response.text
    return state

def build_doc_agent():
    workflow = StateGraph(AgentState)
    workflow.add_node("analyze_diff", analyze_diff)
    workflow.set_entry_point("analyze_diff")
    workflow.add_edge("analyze_diff", END)
    return workflow.compile()

doc_agent = build_doc_agent()