from typing import TypedDict
from langgraph.graph import StateGraph, END
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, SystemMessage
from app.core.config import settings

class AgentState(TypedDict):
    diff: str
    pr_title: str
    pr_number: int
    repo_name: str
    base_branch: str
    head_branch: str
    summary: str

def create_llm():
    return ChatGoogleGenerativeAI(
        model="gemini-1.5-flash",
        google_api_key=settings.gemini_api_key,
        temperature=0.3
    )

def analyze_diff(state: AgentState) -> AgentState:
    llm = create_llm()

    system_prompt = """You are a senior software engineer reviewing a pull request.
Your job is to write a detailed, human-readable summary of the code changes.
You think about WHY changes were made, not just WHAT changed.
You write for two audiences: senior engineers who want depth, and junior developers who need context.
Always respond in the exact markdown format requested."""

    user_prompt = f"""Analyze this pull request and generate a detailed documentation summary.

PR Title: {state['pr_title']}
Repository: {state['repo_name']}
Merging: {state['head_branch']} into {state['base_branch']}

Code diff:
{state['diff'][:8000]}

Respond in exactly this markdown format:

## 🤖 Repo Brain Analysis

### What this PR does
[2-3 sentences explaining the overall purpose and approach. Focus on the WHY, not just the what.]

### Why it matters
[1-2 sentences on the business or technical value of this change. What problem does it solve?]

### What changed in each file
[For each file modified, one bullet point explaining that file's specific role in this change. Be specific about what logic changed, not just that it was modified.]

### Breaking changes
[Any breaking changes, removed functions, changed interfaces, or migration steps needed. Write "None" if there are none.]

### Things to look at
[2-3 specific things a reviewer should pay attention to — potential bugs, hardcoded values, missing error handling, security concerns. Be specific to the actual code, not generic advice.]

---
*Generated by repo-brain · {state['repo_name']} · PR #{state['pr_number']}*"""

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt)
    ]

    response = llm.invoke(messages)
    state["summary"] = response.content
    return state

def build_doc_agent():
    workflow = StateGraph(AgentState)
    workflow.add_node("analyze_diff", analyze_diff)
    workflow.set_entry_point("analyze_diff")
    workflow.add_edge("analyze_diff", END)
    return workflow.compile()

doc_agent = build_doc_agent()